apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zl9vojj4u-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zl9vojj4u-java-springboot-gitops